
async function loadData(){ const r=await fetch('/api/data'); return await r.json(); }
function getLang(){ return localStorage.getItem('nd_lang') || 'de'; }
function setLang(l){ localStorage.setItem('nd_lang', l); location.reload(); }
function t(de,en){ return getLang()==='en' ? (en||de) : de; }
function nav(){ return `<div class="nav"><a href="index.html">Home</a><a href="events.html">${t('Events','Events')}</a><a href="vermietung.html">${t('Vermietung','Rentals')}</a><a href="galerie.html">${t('Galerie','Gallery')}</a><a href="news.html">News</a><a href="kontakt.html">${t('Kontakt','Contact')}</a><a href="impressum.html">${t('Impressum','Legal Notice')}</a><a href="datenschutz.html">${t('Datenschutz','Privacy')}</a><a href="admin.html">Backend</a></div><div class="lang-switch"><button onclick="setLang('de')">DE</button><button onclick="setLang('en')">EN</button></div>`; }
function footer(){return `<footer class="footer"><p>Neudarmstadt · Second-Life-Communityprojekt</p><p><a href="index.html">Home</a><a href="kontakt.html">${t('Kontakt','Contact')}</a><a href="impressum.html">${t('Impressum','Legal Notice')}</a><a href="datenschutz.html">${t('Datenschutz','Privacy')}</a></p><p class="small">Dieses Projekt steht nicht in offizieller Verbindung zu Linden Lab.</p></footer>`}
function cookieBanner(){if(localStorage.getItem('nd_cookie_ok'))return '';return `<div id="cookieBanner" class="cookie-banner"><p>Diese Webseite verwendet technisch notwendige Sitzungs-Cookies für den Admin-Login und speichert Nachrichtenformular-Daten nur zur Bearbeitung deiner Anfrage.</p><button onclick="localStorage.setItem('nd_cookie_ok','1');document.getElementById('cookieBanner').remove()">Verstanden</button> <a class="btn" href="datenschutz.html">Datenschutz</a></div>`}
function appendCommon(){document.body.insertAdjacentHTML('beforeend', footer()+cookieBanner());}
function img(src){ return src || 'assets/landing.png'; }
async function countVisit(){ try{ await fetch('/api/visit', {method:'POST'}); }catch(e){} }

async function renderHome(){
 await countVisit();
 const d=await loadData(); document.body.innerHTML = nav()+`
 <section class="hero" style="background-image:url('${img(d.site.heroImage)}')"><div class="hero-content">
 <img class="logo" src="${img(d.site.logo)}"><div class="subtitle">${d.site.subtitle}</div><h1>${d.site.title}</h1><p class="welcome">${d.site.welcome}</p>
 <div class="visitor-box">👁 ${t('Besucher','Visitors')}: ${d.visitors?.total||0}</div></div></section>
 <section class="section"><h2>${t('Entdecke Neudarmstadt','Discover Neudarmstadt')}</h2><div class="cards">${d.cards.map(c=>`<a class="card" href="${c.link}"><img src="${img(c.image)}"><div class="card-body"><h3>${c.title}</h3><p>${c.text}</p></div></a>`).join('')}</div></section>
 <section class="section"><h2>${t('Aktuelle News','Latest News')}</h2><div class="news-strip">${(d.news||[]).slice(0,3).map(newsCard).join('')}</div></section>
 <section class="section"><h2>${t('Verantwortliche','Team')}</h2>
 <div class="people-mayors">${d.people.filter(p=>p.group==='mayor').map(person).join('')}</div>
 <div class="people-council">${d.people.filter(p=>p.group!=='mayor').map(person).join('')}</div></section>`;
 appendCommon();
}
function safeAttr(v){return String(v||'').replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;')}
function person(p){const on=p.online===true;const ls=p.lastSeen?`<div class="last-seen">${t('Zuletzt aktualisiert','Last update')}: ${new Date(p.lastSeen).toLocaleString()}</div>`:'';return `<div class="person"><img src="${img(p.image)}"><h3>${p.name}</h3><div class="role">${p.role}</div><div class="status ${on?'online':'offline'}"><span class="status-dot"></span>${on?t('Online','Online'):t('Offline','Offline')}</div>${ls}<p class="desc">${getLang()==='en'?(p.description_en||p.description):p.description}</p><button type="button" class="message-btn" data-message-button="1" data-uuid="${safeAttr(p.uuid)}" data-name="${safeAttr(p.name)}">${t('Nachricht senden','Send message')}</button></div>`}
function newsCard(n){return `<div class="news-card"><img src="${img(n.image)}"><div><div class="news-date">${n.date||''}</div><h3>${t(n.title,n.title_en)}</h3><p>${t(n.text,n.text_en)}</p></div></div>`}
function messageModal(){return `<div id="messageModal" class="modal-bg"><div class="modal"><button type="button" class="modal-close" id="msgCloseBtn">X</button><h2>${t('Nachricht senden','Send message')}</h2><p id="recipientText"></p><input id="msgRecipientUuid" type="hidden"><input id="msgRecipientName" type="hidden"><label>${t('Dein Name oder SL-Name','Your name or SL name')}</label><input id="msgSender"><label>${t('E-Mail oder Kontaktinfo optional','Email or contact info optional')}</label><input id="msgContact"><label>${t('Nachricht','Message')}</label><textarea id="msgText"></textarea><button type="button" id="msgSendBtn">${t('Nachricht speichern','Save message')}</button><p id="msgInfo"></p></div></div>`}
function ensureMessageModal(){if(!document.getElementById('messageModal')){document.body.insertAdjacentHTML('beforeend', messageModal());document.getElementById('msgCloseBtn').addEventListener('click', closeMessage);document.getElementById('msgSendBtn').addEventListener('click', sendMessage);}}
function openMessage(uuid,name){ensureMessageModal();document.getElementById('msgRecipientUuid').value=uuid||'';document.getElementById('msgRecipientName').value=name||'';document.getElementById('recipientText').textContent=t('Nachricht an: ','Message to: ')+(name||'');document.getElementById('messageModal').style.display='flex';}
function closeMessage(){const m=document.getElementById('messageModal');if(m)m.style.display='none';}
async function sendMessage(){const body={recipientUuid:document.getElementById('msgRecipientUuid').value,recipientName:document.getElementById('msgRecipientName').value,sender:document.getElementById('msgSender').value,contact:document.getElementById('msgContact').value,text:document.getElementById('msgText').value};let r=await fetch('/api/message',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});document.getElementById('msgInfo').textContent=r.ok?t('Nachricht wurde gespeichert.','Message saved.'):t('Fehler beim Senden.','Error sending message.');if(r.ok){document.getElementById('msgSender').value='';document.getElementById('msgContact').value='';document.getElementById('msgText').value='';}}
document.addEventListener('click',function(e){const b=e.target.closest('[data-message-button]');if(b){openMessage(b.dataset.uuid,b.dataset.name);}});

async function renderEvents(){const d=await loadData(); const events=(d.events||[]).sort((a,b)=>(a.date||'').localeCompare(b.date||'')); document.body.innerHTML=nav()+`<header class="page-head"><h1>${t('Events','Events')}</h1><p>${t('Veranstaltungskalender von Neudarmstadt','Neudarmstadt event calendar')}</p></header><main class="section"><div class="event-toolbar"><input id="eventSearch" placeholder="${t('Event suchen','Search event')}" oninput="filterEvents()"><select id="eventCategory" onchange="filterEvents()"><option value="">${t('Alle Kategorien','All categories')}</option>${[...new Set(events.map(e=>e.category||'Event'))].map(c=>`<option>${c}</option>`).join('')}</select></div><div id="eventGrid" class="grid">${events.map(eventCard).join('')}</div></main>`;appendCommon();}
function eventCard(e){return `<div class="item event-card" data-title="${(e.title+' '+e.description+' '+(e.category||'')).toLowerCase()}" data-cat="${e.category||''}"><span class="event-badge">${e.category||'Event'}</span><img src="${img(e.image)}"><div class="item-body"><div class="date">${e.date||''} · ${e.time||''}</div><h3>${t(e.title,e.title_en)}</h3><div class="event-meta"><span>📍 ${e.location||'Neudarmstadt'}</span></div><p>${t(e.description,e.description_en)}</p></div></div>`}
function filterEvents(){const q=(eventSearch.value||'').toLowerCase(); const c=eventCategory.value; document.querySelectorAll('#eventGrid .item').forEach(el=>{const ok=(!q||el.dataset.title.includes(q))&&(!c||el.dataset.cat===c);el.style.display=ok?'':'none';});}
async function renderRentals(){const d=await loadData(); document.body.innerHTML=nav()+`<header class="page-head"><h1>${t('Vermietung','Rentals')}</h1><p>${t('Häuser, Wohnungen und Läden','Houses, apartments and shops')}</p></header><main class="section"><div class="grid">${d.rentals.map(e=>`<div class="item"><img src="${img(e.image)}"><div class="item-body"><h3>${t(e.title,e.title_en)}</h3><div class="date">${e.price}</div><p>${t(e.description,e.description_en)}</p></div></div>`).join('')}</div></main>`;appendCommon();}
async function renderGallery(){const d=await loadData(); document.body.innerHTML=nav()+`<header class="page-head"><h1>${t('Galerie','Gallery')}</h1><p>${t('Bilder aus Neudarmstadt','Pictures from Neudarmstadt')}</p></header><main class="section"><div class="grid">${d.gallery.map(e=>`<div class="item"><img src="${img(e.image)}"><div class="item-body"><h3>${t(e.title,e.title_en)}</h3><p>${t(e.description,e.description_en)}</p></div></div>`).join('')}</div></main>`;appendCommon();}
async function renderNews(){const d=await loadData(); document.body.innerHTML=nav()+`<header class="page-head"><h1>News</h1><p>${t('Aktuelles aus Neudarmstadt','Latest from Neudarmstadt')}</p></header><main class="section"><div class="news-strip">${(d.news||[]).map(newsCard).join('')}</div></main>`;appendCommon();}
async function renderImpressum(){const d=await loadData(); const l=d.legal||{}; document.body.innerHTML=nav()+`<main class="legal-page"><h1>${t('Impressum','Legal Notice')}</h1><div class="legal-text">${(l.impressumText||'Bitte im Backend eintragen.').replaceAll('<','&lt;')}</div></main>`;appendCommon();}
async function renderDatenschutz(){const d=await loadData(); const l=d.legal||{}; document.body.innerHTML=nav()+`<main class="legal-page"><h1>${t('Datenschutzerklärung','Privacy Policy')}</h1><div class="legal-text">${(l.privacyText||'Bitte im Backend eintragen.').replaceAll('<','&lt;')}</div></main>`;appendCommon();}
async function renderKontakt(){const d=await loadData(); const l=d.legal||{}; document.body.innerHTML=nav()+`<main class="legal-page"><h1>${t('Kontakt','Contact')}</h1><p>${t('Du kannst die Verantwortlichen direkt über die Buttons unter den Profilen auf der Startseite anschreiben.','You can contact the team using the buttons under the profiles on the homepage.')}</p><h2>${t('Allgemeiner Kontakt','General contact')}</h2><p>E-Mail: ${l.email||'Bitte im Backend eintragen'}</p></main>`;appendCommon();}
