
async function loadData(){ const r=await fetch('/api/data'); return await r.json(); }
function nav(){ return `<div class="nav"><a href="index.html">Home</a><a href="events.html">Events</a><a href="vermietung.html">Vermietung</a><a href="galerie.html">Galerie</a><a href="kontakt.html">Kontakt</a><a href="impressum.html">Impressum</a><a href="datenschutz.html">Datenschutz</a><a href="admin.html">Backend</a></div>`; }
function img(src){ return src || 'assets/landing.png'; }
async function renderHome(){
 const d=await loadData(); document.body.innerHTML = nav()+`
 <section class="hero" style="background-image:url('${img(d.site.heroImage)}')"><div class="hero-content">
 <img class="logo" src="${img(d.site.logo)}"><div class="subtitle">${d.site.subtitle}</div><h1>${d.site.title}</h1><p class="welcome">${d.site.welcome}</p></div></section>
 <section class="section"><h2>Entdecke Neudarmstadt</h2><div class="cards">${d.cards.map(c=>`<a class="card" href="${c.link}"><img src="${img(c.image)}"><div class="card-body"><h3>${c.title}</h3><p>${c.text}</p></div></a>`).join('')}</div></section>
 <section class="section"><h2>Verantwortliche</h2>
 <div class="people-mayors">${d.people.filter(p=>p.group==='mayor').map(person).join('')}</div>
 <div class="people-council">${d.people.filter(p=>p.group!=='mayor').map(person).join('')}</div></section>`;
 appendCommon();
}
function person(p){const on=p.online===true;return `<div class="person"><img src="${img(p.image)}"><h3>${p.name}</h3><div class="role">${p.role}</div><div class="status ${on?'online':'offline'}"><span class="status-dot"></span>${on?'Online':'Offline'}</div><p class="desc">${p.description}</p><button class="message-btn" onclick="openMessage('${String(p.uuid||'').replaceAll("'",'')}','${String(p.name||'').replaceAll("'",'\'')}')">Nachricht senden</button></div>`}

function messageModal(){return `<div id="messageModal" class="modal-bg"><div class="modal"><button class="modal-close" onclick="closeMessage()">X</button><h2>Nachricht senden</h2><p id="recipientText"></p><input id="msgRecipientUuid" type="hidden"><input id="msgRecipientName" type="hidden"><label>Dein Name oder SL-Name</label><input id="msgSender" placeholder="Dein Name"><label>E-Mail oder Kontaktinfo optional</label><input id="msgContact" placeholder="Optional"><label>Nachricht</label><textarea id="msgText" placeholder="Deine Nachricht"></textarea><button onclick="sendMessage()">Nachricht speichern</button><p id="msgInfo"></p></div></div>`}
function openMessage(uuid,name){document.body.insertAdjacentHTML('beforeend', document.getElementById('messageModal')?'':messageModal());msgRecipientUuid.value=uuid;msgRecipientName.value=name;recipientText.textContent='Nachricht an: '+name;messageModal.style.display='flex';}
function closeMessage(){messageModal.style.display='none';}
async function sendMessage(){const body={recipientUuid:msgRecipientUuid.value,recipientName:msgRecipientName.value,sender:msgSender.value,contact:msgContact.value,text:msgText.value};let r=await fetch('/api/message',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});msgInfo.textContent=r.ok?'Nachricht wurde gespeichert.':'Fehler beim Senden.';if(r.ok){msgSender.value='';msgContact.value='';msgText.value='';}}

async function renderEvents(){const d=await loadData(); document.body.innerHTML=nav()+`<header class="page-head"><h1>Events</h1><p>Veranstaltungskalender von Neudarmstadt</p></header><main class="section"><div class="grid">${d.events.map(e=>`<div class="item"><img src="${img(e.image)}"><div class="item-body"><div class="date">${e.date} · ${e.time}</div><h3>${e.title}</h3><p>${e.description}</p></div></div>`).join('')}</div></main>`}
async function renderRentals(){const d=await loadData(); document.body.innerHTML=nav()+`<header class="page-head"><h1>Vermietung</h1><p>Häuser, Wohnungen und Läden</p></header><main class="section"><div class="grid">${d.rentals.map(e=>`<div class="item"><img src="${img(e.image)}"><div class="item-body"><h3>${e.title}</h3><div class="date">${e.price}</div><p>${e.description}</p></div></div>`).join('')}</div></main>`}
async function renderGallery(){const d=await loadData(); document.body.innerHTML=nav()+`<header class="page-head"><h1>Galerie</h1><p>Bilder aus Neudarmstadt</p></header><main class="section"><div class="grid">${d.gallery.map(e=>`<div class="item"><img src="${img(e.image)}"><div class="item-body"><h3>${e.title}</h3><p>${e.description}</p></div></div>`).join('')}</div></main>`}

function footer(){return `<footer class="footer"><p>Neudarmstadt · Second-Life-Communityprojekt</p><p><a href="index.html">Home</a><a href="kontakt.html">Kontakt</a><a href="impressum.html">Impressum</a><a href="datenschutz.html">Datenschutz</a></p><p class="small">Dieses Projekt steht nicht in offizieller Verbindung zu Linden Lab.</p></footer>`}
function cookieBanner(){if(localStorage.getItem('nd_cookie_ok'))return '';return `<div id="cookieBanner" class="cookie-banner"><p>Diese Webseite verwendet technisch notwendige Sitzungs-Cookies für den Admin-Login und speichert Nachrichtenformular-Daten nur zur Bearbeitung deiner Anfrage.</p><button onclick="localStorage.setItem('nd_cookie_ok','1');document.getElementById('cookieBanner').remove()">Verstanden</button> <a class="btn" href="datenschutz.html">Datenschutz</a></div>`}
function appendCommon(){document.body.insertAdjacentHTML('beforeend', footer()+cookieBanner());}
async function renderImpressum(){const d=await loadData(); const l=d.legal||{}; document.body.innerHTML=nav()+`<main class="legal-page"><h1>Impressum</h1><p><strong>Angaben gemäß § 5 DDG</strong></p><p>${l.ownerName||'Bitte eintragen'}<br>${(l.address||'Bitte vollständige Anschrift eintragen').replaceAll('\n','<br>')}</p><h2>Kontakt</h2><p>E-Mail: ${l.email||'Bitte eintragen'}</p><h2>Verantwortlich für den Inhalt</h2><p>${l.responsible||l.ownerName||'Bitte eintragen'}</p><h2>Hinweis zu Second Life</h2><p>${l.projectNote||'Neudarmstadt ist ein privates Second-Life-Projekt.'}</p><h2>Haftung für Inhalte</h2><p>Die Inhalte dieser Webseite wurden sorgfältig erstellt. Für die Richtigkeit, Vollständigkeit und Aktualität der Inhalte wird jedoch keine Gewähr übernommen.</p><h2>Bildrechte</h2><p>Alle verwendeten Bilder, Logos und Grafiken dürfen nur genutzt werden, wenn die entsprechenden Nutzungsrechte vorliegen.</p></main>`;appendCommon();}
async function renderDatenschutz(){const d=await loadData(); const l=d.legal||{}; document.body.innerHTML=nav()+`<main class="legal-page"><h1>Datenschutzerklärung</h1><h2>Verantwortliche Stelle</h2><p>${l.ownerName||'Bitte eintragen'}<br>${(l.address||'Bitte Anschrift eintragen').replaceAll('\n','<br>')}<br>E-Mail: ${l.email||'Bitte eintragen'}</p><h2>Allgemeines</h2><p>Diese Webseite verarbeitet personenbezogene Daten nur, soweit dies für den Betrieb der Webseite, den Admin-Login und die Bearbeitung von Nachrichten erforderlich ist.</p><h2>Nachrichtenformular</h2><p>Wenn Besucher eine Nachricht an Verantwortliche senden, werden Empfänger, Name/SL-Name, optionale Kontaktangabe, Nachrichtentext und Zeitpunkt gespeichert. Die Daten werden ausschließlich zur Bearbeitung der Anfrage verwendet.</p><h2>Admin-Login und technisch notwendige Cookies</h2><p>Für den geschützten Backend-Bereich wird ein technisch notwendiges Sitzungs-Cookie verwendet. Dieses dient ausschließlich der Anmeldung im Backend.</p><h2>Server- und Zugriffsdaten</h2><p>Beim Betrieb auf einem Webserver können technisch notwendige Zugriffsdaten wie IP-Adresse, Datum, Uhrzeit, Browser und aufgerufene Seite verarbeitet werden. Diese Daten dienen der Sicherheit und Funktionsfähigkeit der Webseite.</p><h2>Rechtsgrundlagen</h2><p>Die Verarbeitung erfolgt je nach Zweck auf Grundlage von Art. 6 Abs. 1 lit. b DSGVO, Art. 6 Abs. 1 lit. f DSGVO oder einer Einwilligung, sofern eine solche eingeholt wird.</p><h2>Speicherdauer</h2><p>Nachrichten werden nur so lange gespeichert, wie sie für die Bearbeitung erforderlich sind, und können im Backend gelöscht werden.</p><h2>Rechte betroffener Personen</h2><p>Betroffene Personen haben im Rahmen der gesetzlichen Vorgaben Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung, Datenübertragbarkeit und Widerspruch.</p><h2>Keine externen Tracker</h2><p>Diese Version der Webseite enthält keine externen Analyse- oder Werbetracker.</p></main>`;appendCommon();}
async function renderKontakt(){const d=await loadData(); const l=d.legal||{}; document.body.innerHTML=nav()+`<main class="legal-page"><h1>Kontakt</h1><p>Du kannst die Verantwortlichen direkt über die Buttons unter den Profilen auf der Startseite anschreiben.</p><h2>Allgemeiner Kontakt</h2><p>E-Mail: ${l.email||'Bitte im Backend eintragen'}</p><h2>Datenschutzhinweis</h2><p>Übermittelte Nachrichten werden gespeichert, damit sie bearbeitet werden können. Weitere Informationen findest du in der Datenschutzerklärung.</p></main>`;appendCommon();}
